/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface AuthDto {
  exp?: number
  iat?: number
  pid?: number
}
export function sign(dto: AuthDto): string | null
export function verify(token: string): AuthDto | null
export function signStr(payload: string): string | null
export function verifyStr(token: string): string | null
